export const BOTTLE_DETAILS_REQUEST = "BOTTLE_DETAILS_REQUEST"
export const BOTTLE_DETAILS_SUCCESS = "BOTTLE_DETAILS_SUCCESS"
export const BOTTLE_DETAILS_FAIL = "BOTTLE_DETAILS_FAIL"

export const BOTTLE_WEIGHT_REQUEST = "BOTTLE_WEIGHT_REQUEST"
export const BOTTLE_WEIGHT_SUCCESS = "BOTTLE_WEIGHT_SUCCESS"
export const BOTTLE_WEIGHT_FAIL = "BOTTLE_WEIGHT_FAIL"