export const BOTTLE_DETAILS_REQUEST = "BOTTLE_DETAILS_REQUEST"
export const BOTTLE_DETAILS_SUCCESS = "BOTTLE_DETAILS_SUCCESS"
export const BOTTLE_DETAILS_FAIL = "BOTTLE_DETAILS_FAIL"

export const BOTTLE_WEIGHT_REQUEST = "BOTTLE_WEIGHT_REQUEST"
export const BOTTLE_WEIGHT_SUCCESS = "BOTTLE_WEIGHT_SUCCESS"
export const BOTTLE_WEIGHT_FAIL = "BOTTLE_WEIGHT_FAIL"

export const BOTTLE_SET_WEIGHT_REQUEST = "BOTTLE_SET_WEIGHT_REQUEST"
export const BOTTLE_SET_WEIGHT_SUCCESS = "BOTTLE_SET_WEIGHT_SUCCESS"
export const BOTTLE_SET_WEIGHT_FAIL = "BOTTLE_SET_WEIGHT_FAIL"
export const BOTTLE_SET_WEIGHT_RESET = "BOTTLE_SET_WEIGHT_RESET"

export const BOTTLE_CREATE_REQUEST = "BOTTLE_CREATE_REQUEST"
export const BOTTLE_CREATE_SUCCESS = "BOTTLE_CREATE_SUCCESS"
export const BOTTLE_CREATE_FAIL = "BOTTLE_CREATE_FAIL"

export const BOTTLE_CREATE_USED_REQUEST = "BOTTLE_CREATE_USED_REQUEST"
export const BOTTLE_CREATE_USED_SUCCESS = "BOTTLE_CREATE_USED_SUCCESS"
export const BOTTLE_CREATE_USED_FAIL = "BOTTLE_CREATE_USED_FAIL"

export const BOTTLE_SET_FOLIO_REQUEST = "BOTTLE_SET_FOLIO_REQUEST"
export const BOTTLE_SET_FOLIO_SUCCESS = "BOTTLE_SET_FOLIO_SUCCESS"
export const BOTTLE_SET_FOLIO_RESET = "BOTTLE_SET_FOLIO_RESET"

export const BOTTLE_SET_CUSTOM_FOLIO_REQUEST = "BOTTLE_SET_CUSTOM_FOLIO_REQUEST"
export const BOTTLE_SET_CUSTOM_FOLIO_SUCCESS = "BOTTLE_SET_CUSTOM_FOLIO_SUCCESS"
export const BOTTLE_SET_CUSTOM_FOLIO_RESET = "BOTTLE_SET_CUSTOM_FOLIO_RESET"

export const BOTTLE_CREATE_TYPE_SUCCESS = "BOTTLE_CREATE_TYPE_SUCCESS"
export const BOTTLE_CREATE_TYPE_RESET = "BOTTLE_CREATE_TYPE_RESET"