export const QUICK_COUNTS_LIST_REQUEST = 'QUICK_COUNTS_LIST_REQUEST'
export const QUICK_COUNTS_LIST_SUCCESS = 'QUICK_COUNTS_LIST_SUCCESS'
export const QUICK_COUNTS_LIST_FAIL = 'QUICK_COUNTS_LIST_FAIL'

export const TOTAL_COUNTS_LIST_REQUEST = 'TOTAL_COUNTS_LIST_REQUEST'
export const TOTAL_COUNTS_LIST_SUCCESS = 'TOTAL_COUNTS_LIST_SUCCESS'
export const TOTAL_COUNTS_LIST_FAIL = 'TOTAL_COUNTS_LIST_FAIL'

export const COUNT_TYPE_SUCCESS = 'COUNT_TYPE_SUCCESS'

export const CREATE_QUICK_COUNT_REQUEST = "CREATE_QUICK_COUNT_REQUEST"
export const CREATE_QUICK_COUNT_SUCCESS = "CREATE_QUICK_COUNT_SUCCESS"
export const CREATE_QUICK_COUNT_FAIL = "CREATE_QUICK_COUNT_FAIL"

export const CREATE_TOTAL_COUNT_REQUEST = "CREATE_TOTAL_COUNT_REQUEST"
export const CREATE_TOTAL_COUNT_SUCCESS = "CREATE_TOTAL_COUNT_SUCCESS"
export const CREATE_TOTAL_COUNT_FAIL = "CREATE_TOTAL_COUNT_FAIL"

export const COUNT_SUMMARY_REQUEST = "COUNT_SUMMARY_REQUEST"
export const COUNT_SUMMARY_SUCCESS = "COUNT_SUMMARY_SUCCESS"
export const COUNT_SUMMARY_FAIL = "COUNT_SUMMARY_FAIL"

export const COUNT_ACTIVE_SUCCESS = "COUNT_ACTIVE_SUCCESS"

export const BOTTLE_COUNT_DETAILS_REQUEST = "BOTTLE_COUNT_DETAILS_REQUEST"
export const BOTTLE_COUNT_DETAILS_SUCCESS = "BOTTLE_COUNT_DETAILS_SUCCESS"
export const BOTTLE_COUNT_DETAILS_FAIL = "BOTTLE_COUNT_DETAILS_FAIL"

export const UPDATE_BOTTLE_WEIGHT_REQUEST = "UPDATE_BOTTLE_WEIGHT_REQUEST"
export const UPDATE_BOTTLE_WEIGHT_SUCCESS = "UPDATE_BOTTLE_WEIGHT_SUCCESS"
export const UPDATE_BOTTLE_WEIGHT_FAIL = "UPDATE_BOTTLE_WEIGHT_FAIL"

export const UPDATE_BOTTLE_STATE_REQUEST = "UPDATE_BOTTLE_STATE_REQUEST"
export const UPDATE_BOTTLE_STATE_SUCCESS = "UPDATE_BOTTLE_STATE_SUCCESS"
export const UPDATE_BOTTLE_STATE_FAIL = "UPDATE_BOTTLE_STATE_FAIL"

export const SET_COUNT_ID_SUCCESS = "SET_COUNT_ID_SUCCESS"