export const QUICK_COUNTS_LIST_REQUEST = 'QUICK_COUNTS_LIST_REQUEST'
export const QUICK_COUNTS_LIST_SUCCESS = 'QUICK_COUNTS_LIST_SUCCESS'
export const QUICK_COUNTS_LIST_FAIL = 'QUICK_COUNTS_LIST_FAIL'

export const TOTAL_COUNTS_LIST_REQUEST = 'TOTAL_COUNTS_LIST_REQUEST'
export const TOTAL_COUNTS_LIST_SUCCESS = 'TOTAL_COUNTS_LIST_SUCCESS'
export const TOTAL_COUNTS_LIST_FAIL = 'TOTAL_COUNTS_LIST_FAIL'

export const COUNT_TYPE_SUCCESS = 'COUNT_TYPE_SUCCESS'

