export const STOCK_PRODUCT_LIST_REQUEST = "STOCK_PRODUCT_LIST_REQUEST"
export const STOCK_PRODUCT_LIST_SUCCESS = "STOCK_PRODUCT_LIST_SUCCESS"
export const STOCK_PRODUCT_LIST_FAIL = "STOCK_PRODUCT_LIST_FAIL"