export const GET_YIELD_REPORT_REQUEST = "GET_YIELD_REPORT_REQUEST"
export const GET_YIELD_REPORT_SUCCESS = "GET_YIELD_REPORT_SUCCESS"
export const GET_YIELD_REPORT_FAIL = "GET_YIELD_REPORT_FAIL"

export const GET_YIELD_REPORTS_REQUEST = "GET_YIELD_REPORTS_REQUEST"
export const GET_YIELD_REPORTS_SUCCESS = "GET_YIELD_REPORTS_SUCCESS"
export const GET_YIELD_REPORTS_FAIL = "GET_YIELD_REPORTS_FAIL"

export const SET_YIELD_REPORT_ID_SUCCESS = "SET_YIELD_REPORT_ID_SUCCESS"

export const GET_YIELD_SALES_DATA_REQUEST = "GET_YIELD_SALES_DATA_REQUEST"
export const GET_YIELD_SALES_DATA_SUCCESS = "GET_YIELD_SALES_DATA_SUCCESS"
export const GET_YIELD_SALES_DATA_FAIL = "GET_YIELD_SALES_DATA_FAIL"

export const SET_YIELD_ID_SUCCESS = "SET_YIELD_ID_SUCCESS"
